# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-JavaScript-UCS
version:      0.01
version_from: lib/Encode/JavaScript/UCS.pm
installdirs:  site
requires:
    Encode:                        2.12
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
